### ISSUE TITLE
Is there SDK for alipay or wechat-pay?

### ISSUE THREAD

**Issue by 9PEAK** [univapay/univapay-php-sdk#20]
I've got a api doc for alipay and wechat-pay from Univapay, but the docs are Japanese, I can't read Japanese.

**Comment by kgston** [comment]
You can refer to the docs in English: https://docs.univapay.com/en/References/reference/
The PHP SDK supports alipay and wechat-pay for online payments.

**Comment by 9PEAK** [comment]
Thanks, however I use the doc that the univapay manager sended to me instead. I uploaded the doc file:
http://qiniu-demo.9peak.net/alipay_v1_0_7.pdf

I copied the demo code of payment, reset the param, submit the form. The page goes to alipay.  Payment is success.

But It failed with both get and post method when I used the demo code of Refund, Error Code is ERG01P05P07.

`
◆商品金額1000円、送料500円の商品を全額取消す場合のフォームタグ
<form action="https://gw.ccps.jp/payment.aspx" method="get">
<input type="hidden" name="sid" value="（店舗ID）">
<input type="hidden" name="svid" value="6">
<input type="hidden" name="ptype" value="1">
<input type="hidden" name="job" value="CANCEL">
<input type="txt" name="pid" value="（決済ID）">
<input type="submit" value="Alipay決済フォームへ">
</form> 
`

The Error Code doc( https://link.upc-app.com/doc/errorsummary.pdf ) shows

> エラーコード（末尾6桁） ： ER***P05P07
> エラー内容： 送信元IPのエラー
> 対応法： 管理画面の送信元IP設定をご確認ください。 ※解説①参照

My app is an http website, and the payment is success.
So I think my config setting for "設定 --- Alipay設定 --- Alipay決済データ送信元URL" in "https://cp.ccps.jp/" is correct, while the "決済データ送信元IP" is not nessesary and I leave it blank.
By the way, I tried to set my server ip as "決済データ送信元IP", ERROR is the same.

How to fix my problem? HELP.

**Comment by 9PEAK** [comment]
The demo code of Refund is here

◆商品金額1000円、送料500円の商品を全額取消す場合のフォームタグ 

`
<form action="https://gw.ccps.jp/payment.aspx" method="get">
<input type="hidden" name="sid" value="（店舗ID）">
<input type="hidden" name="svid" value="6">
<input type="hidden" name="ptype" value="1">
<input type="hidden" name="job" value="CANCEL">
<input type="txt" name="pid" value="（決済ID）">
<input type="submit" value="Alipay決済フォームへ">
</form> `

**Comment by 9PEAK** [comment]
pandahime.com@gmail.com
thanks for your help~

**Comment by Timzhaihui** [comment]
> Thanks, however I use the doc that the univapay manager sended to me instead. I uploaded the doc file: http://qiniu-demo.9peak.net/alipay_v1_0_7.pdf
> 
> I copied the demo code of payment, reset the param, submit the form. The page goes to alipay. Payment is success.
> 
> But It failed with both get and post method when I used the demo code of Refund( http://qiniu-demo.9peak.net/univapay-alipay-refund.png ), Error Code is ERG01P05P07.
> 
> The Error Code doc( https://link.upc-app.com/doc/errorsummary.pdf ) shows
> 
> > エラーコード（末尾6桁） ： ER***P05P07
> > エラー内容： 送信元IPのエラー
> > 対応法： 管理画面の送信元IP設定をご確認ください。 ※解説①参照
> 
> My app is an http website, and the payment is success. So I think my config setting for "設定 --- Alipay設定 --- Alipay決済データ送信元URL" in "https://cp.ccps.jp/" is correct, while the "決済データ送信元IP" is not nessesary and I leave it blank. By the way, I tried to set my server ip as "決済データ送信元IP", it is the same error still.
> 
> How to fix my problem? HELP.

Hi 
thanks for your question.
you cannot leave "決済データ送信元IP" blank, it is an mandatory field in your case.
If you still get the some error code after you set the IP address, you may have to check if you set the right IP.
By the way, may i have you store id and store name so that i can check the setting for you?

**Comment by kgston** [comment]
In order to follow up on your question, it would involve further discussions including sensitive IDs and confidential documentation. So we would like to move this discussion over to email. I will close this issue now since it is not relevant to the PHP SDK itself.
