### ISSUE TITLE
リンクフォームから作成した定期課金情報の取得時にエラー

### ISSUE THREAD

**Issue by HayatoIida-CS** [univapay/univapay-php-sdk#41]
お世話になっております。

リンクフォームに商品を設定して作成した定期課金の場合、定期課金情報の取得で

 ```PHP
// Univapay\UnivapayClient
$univapayClient->getSubscription($storeId, $subscriptionId)
```
を呼び出した際にエラーが発生するようです。

エラー内容は次の通りです。
```
Univapay\Utility\Json\NoSuchPathException with message 'Error at path period'
```

定期課金情報が取得できないことにより、ウェブフックを受けてシステム側で契約を更新することができず困っております。
以下に詳細情報を記載させていただきますので、ご調査いただけますと幸いです。

## 詳細情報
* 使用しているSDKのバージョン：6.4.0
* リンクフォーム
    * CVV認証あり
    * 商品を設定
        * 課金間隔：毎月
        * 初回課金金額：1078 JPY
        * 定期課金金額：1078 JPY

**Comment by kgston** [comment]
ご報告ありがとうございます。
定期課金ID（`subscription_id`）をいただけますか？

**Comment by HayatoIida-CS** [comment]
@kgston 
ご対応いただきありがとうございました。
バージョン 6.5.0 にアップデートしたところ、発生しなくなりました。

もう不要かと思いますが、一応テストで使用していた定期課金IDは以下となります。
11ee21e7-93cf-506c-b23c-c3d15aefa86d

**Comment by kgston** [comment]
ご返信ありがとうございます。
IDを確認したところ、6.5.0の修正で問題は解決します。
