### ISSUE TITLE
新システムの以降について

### ISSUE THREAD

**Issue by kyohey-dan** [univapay/univapay-php-sdk#45]
新システムの移行についてユニヴァペイさんに問い合わせたところ、こちらを教えていただきましたので、
こちらから質問させていただきます。
前提として、あまり技術的にわかっていないものになります。
決済機能について質問です。
提供されている新システムのドキュメントには、インラインフォームとウィジェットが掲載してあり、
わたしたちは、インラインフォームでの開発かと思うのですが、JSでの処理しか掲載がなく困っております。
現在のサイトでは、カード情報を入力する箇所に<script src="https://token.ccps.jp/UpcTokenPaymentMini.js"></script> を設置したり、
会員の情報や加入プランなどを送信する際に、PHP側にて、その情報をクレジットカードの決済ゲートウェイ（https://gw.ccps.jp/memberpay.aspx）にリクエストを送り、
その結果を受け取り、独自の管理DBに保存・管理できるようにしています。
この仕組みを新しい、ユニヴァペイさんのシステムで動作するようにしたいとき、どういった方法をとればいいでしょうか？
現在処理はPHPで行っているため、PHPでの処理を行いたいです。

よろしくお願いします。

[php.txt](https://github.com/univapay/univapay-php-sdk/files/12911607/php.txt)

**Comment by upc-tanaka** [comment]
お世話になっております。

> PHP側にて、その情報をクレジットカードの決済ゲートウェイ（[https://gw.ccps.jp/memberpay.aspx）にリクエストを送り、
その結果を受け取り、独自の管理DBに保存・管理できるようにしています。

新システムではJSの処理で、インラインフォームなどのフォーム上からカード情報をトークン化する処理を行う必要がございます。
トークン化について：https://docs.univapay.com/payment-tokenization/
JSでのパラメータ実装について：https://docs.univapay.com/set-inline/

その後、PHP-SDKの結果取得オブジェクトやコールバック、ウェブフックなどからトークン化したカード情報を取得し、御社のDBに保存する運用になると思われます。

その後はSDKを用いて、課金処理などを行っていただくことができます。

よろしくお願いいたします。

※トークン取得例

```
<script src="https://widget.univapay.com/client/checkout.js"></script>
<span   data-app-id="アプリトークンID"
        data-checkout="token"
        data-token-type="recurring"
        data-cvv-authorize="true"
        data-inline="true">
</span>
```

**Comment by kyohey-dan** [comment]
@upc-tanaka 
upc-tanaka様
お世話になっております。
ご返信ありがとうございます。

PHP-SDKがよくわからず教えていただきたいです。大変申し訳ございません。
なにかSDKについてのドキュメントがありますでしょうか？

一応、GithubのREADMEやexsamplesをみたのですが、私のいまのコードにどう落とし込めばいいのかが不明です...

それぞれのプロジェクトでコードは異なるとは思うのですが...
お手間取らせて申し訳ございませんが、もうすこし具体的なコードでいただくことは可能でしょうか？
コードの説明もいただれば助かります。

**Comment by kyohey-dan** [comment]
@upc-tanaka 
こんにちは。
さきほどからすこし、コードを触りまして、現在のユーザーなどのデータは取得することができました。
つぎにテスト課金をして、新システムの管理画面に表示したいと思い、処理を書いているのですが、
PHPで実行すると、以下のエラーが表示されます。

現在のコードも添付させていただきますのでご確認よろしくお願いします。

■エラー
Fatal error: Uncaught Univapay\Errors\UnivapayRequestError: Array
(
    [url] => https://api.univapay.com/tokens
    [http_status] => 400
    [status] => error
[test_univapay.txt](https://github.com/univapay/univapay-php-sdk/files/12923972/test_univapay.txt)

    [code] => VALIDATION_ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [field] => data.country
                    [reason] => INVALID_FORMAT_COUNTRY
                )

        )

)
 in /php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php:29
Stack trace:
#0 /php-sdk/vendor/univapay/php-sdk/src/Univapay/Utility/HttpUtils.php(43): Univapay\Errors\UnivapayRequestError::fromJson('https://api.uni...', Array)
#1/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/HttpRequester.php(34): Univapay\Utility\HttpUtils::checkResponse(Object(WpOrg\Requests\Response))
#2/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/Handlers/BasicRetryHandler.php(28): Univapay\Requests\HttpRequester->Uni in /php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php on line 29

**Comment by kyohey-dan** [comment]
@upc-tanaka
こんにちは。
さきほどからすこし、コードを触りまして、現在のユーザーなどのデータは取得することができました。
つぎにテスト課金をして、新システムの管理画面に表示したいと思い、処理を書いているのですが、
PHPで実行すると、以下のエラーが表示されます。

現在のコードも添付させていただきますのでご確認よろしくお願いします。

■エラー
Fatal error: Uncaught Univapay\Errors\UnivapayRequestError: Array
(
[url] => https://api.univapay.com/tokens
[http_status] => 400
[status] => error

[code] => VALIDATION_ERROR
[errors] => Array
    (
        [0] => Array
            (
                [field] => data.country
                [reason] => INVALID_FORMAT_COUNTRY
            )

    )
)
in /php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php:29
Stack trace:
#0 /php-sdk/vendor/univapay/php-sdk/src/Univapay/Utility/HttpUtils.php(43): Univapay\Errors\UnivapayRequestError::fromJson('https://api.uni/...', Array)
https://github.com/univapay/univapay-php-sdk/pull/1/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/HttpRequester.php(34): Univapay\Utility\HttpUtils::checkResponse(Object(WpOrg\Requests\Response))
https://github.com/univapay/univapay-php-sdk/pull/2/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/Handlers/BasicRetryHandler.php(28): Univapay\Requests\HttpRequester->Uni in /php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php on line 29

[test_univapay.txt](https://github.com/univapay/univapay-php-sdk/files/12923980/test_univapay.txt)

**Comment by upc-tanaka** [comment]
@kyohey-dan 
お世話になっております。
確認いたしましたところ、下記記述の国コードにおけるエラーが発生していると思われます。
https://docs.univapay.com/References/error-codes/#:~:text=INVALID_FORMAT_COUNTRY
ISO 3166-1形式で、日本は大文字で 'JP' になると思いますので小文字から修正して再度リクエストを送信していただけますでしょうか。
よろしくお願いいたします。

```
  new Address(
    'Minato-ku, Roppongi, 3-16-35', // 住所１
    'East Roppongi building 2F', // 住所２
    'Tokyo', // 市町村区
    'jp', // 国
    '1060032' // 郵便番号
  )
```

**Comment by kyohey-dan** [comment]
@upc-tanaka 
お世話になっております。
ありがとうございます！
ただ添付のように直しましたが、以下のように同じエラーがでております...

---

Fatal error: Uncaught Univapay\Errors\UnivapayRequestError: Array
(
    [url] => https://api.univapay.com/tokens
    [http_status] => 400
    [status] => error
    [code] => VALIDATION_ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [field] => data.country
                    [reason] => INVALID_FORMAT_COUNTRY
                )

        )

)
 in /Users/kyohei_dan/code/dev/php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php:29
Stack trace:
#0 /Users/kyohei_dan/code/dev/php-sdk/vendor/univapay/php-sdk/src/Univapay/Utility/HttpUtils.php(43): Univapay\Errors\UnivapayRequestError::fromJson('https://api.uni...', Array)
#1 /Users/kyohei_dan/code/dev/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/HttpRequester.php(34): Univapay\Utility\HttpUtils::checkResponse(Object(WpOrg\Requests\Response))
#2 /Users/kyohei_dan/code/dev/php-sdk/vendor/univapay/php-sdk/src/Univapay/Requests/Handlers/BasicRetryHandler.php(28): Univapay\Requests\HttpRequester->Uni in /Users/kyohei_dan/code/dev/php-sdk/vendor/univapay/php-sdk/src/Univapay/Errors/UnivapayRequestError.php on line 29
[test_univapay.txt](https://github.com/univapay/univapay-php-sdk/files/12925084/test_univapay.txt)

**Comment by upc-tanaka** [comment]
お世話になっております。
state（都道府県）,city（市区町村） が併せて正確に入力できていない為エラーが発生していると思われます。
下記の例を参考に位置がずれていないか再度確認していただけないでしょうか。
よろしくお願いいたします。

`
    'Roppongi, 3-16-35', // 住所１
    'East Roppongi building 2F', // 住所２
    'Tokyo', // 都道府県
    'Minato-ku', // 市区町村
    'jp', // 国
    '1060032' // 郵便番号`

**Comment by kyohey-dan** [comment]
@upc-tanaka 
お世話になっております。
ご返信ありがとうございます。

上記いただいた内容でテスト課金がローカル環境からできました。
次の質問なのですが、
現在稼働中のサイトが入力ページ（/input）→確認ページ（/confirm）→完了ページ（/thanks）というページ遷移構成でして、
入力ページ（/input）で、クレジットカード情報を入力する箇所があり、以下のようにコードを書いております。

`<script src="https://widget.univapay.com/client/checkout.js"></script>
<form id="payment-form" action="">
  <div id="checkout">
    <span data-email="false" data-checkout="payment" data-token-type="subscription" data-subscription-period="monthly" data-amount="1" data-currency="jpy" data-cvv-authorize="true" data-inline="true" data-app-id="アプリトークンID">
    </span>
  </div>
  <button type="submit">Pay</button>
</form>
`

ただ、ここで内容送信ではなく、内容を確認するボタンがあり、それを押すと確認ページ（/confirm）へ遷移します。
そのときのid="checkout"の中のspan要素はどのように書いたらいいでしょうか？

また、カード情報をトークン化するコードはどのページのファイルへ記述すればいいのでしょうか？（入力ページ?確認ページ?完了ページ?）
