### ISSUE TITLE
新管理画面に登録してある商品を取得して課金を実行したい。

### ISSUE THREAD

**Issue by kyohey-dan** [univapay/univapay-php-sdk#46]
@upc-tanaka 
お世話になっております。
現在商品に以下のようにさまざまなプランを用意しています。

■商品一覧
①10万円コース月払い（100回） | 定期課金 | ¥1,000JPY |  
②10万コース / 1000円 100回 | 回数制限付き定期課金 | ¥1,000JPY |  
④ 10万コース / 半年掛 | 回数制限付き定期課金 | ¥11,000JPY |  
⑤10万コース /年掛 | 回数制限付き定期課金 | ¥22,000JPY |  
⑥18万コース / 月掛 | 回数制限付き定期課金 | ¥2,000JPY |  

■現在のPHPコード
添付をごらんください。
processPayment関数とexecutePayment関数を使用してトークン化やダミーの決済実行はできております。

■質問
実際のサイトでユーザーが選択した商品に合わせて決済を実行する場合、exsamplesに記載のあった、
以下のようなコードで商品を取得して、
その商品をexecutePayment関数で指定して簡単に決済できる方法などはありますでしょうか？
```
$subscriptions = $client->listSubscriptions();
if (sizeof($subscriptions->items) > 0) {
    $subscription = current($subscriptions->items)->fetch();
    $client->getSubscription($subscription->storeId, $subscription->id);
}
```
[process_payment.txt](https://github.com/univapay/univapay-php-sdk/files/13049863/process_payment.txt)

**Comment by upc-tanaka** [comment]
@kyohey-dan 
お世話になっております。
現時点では申し訳ございませんが、
PHP SDKを利用した商品アイテムの課金は未対応となります。
いただきました要望はスケジュールが調整できましたら必要に応じて随時反映させていただきます。
宜しくお願い致します。

**Comment by kyohey-dan** [comment]
@upc-tanaka 
お世話になっております。
お返事ありがとうございます。

PHP SDKで商品を取得してそれをもとに課金ができないことは理解できました！

続けて質問なのですが、
■質問①
現在、processPayment関数（トークン化）とexecutePayment関数（決済実行）を使用してトークン化やダミーの決済実行はできております。
ダミーで決済ができているということは、コード内のダミー金額の部分や、まだわかっていませんが、商品IDを指定して、
課金できるということでしょうか？

function executePayment($tokenResource)
{
  // テスト環境用のアプリトークン
  $token = '';
  $secret = '';

  $storeAppToken = AppJWT::createToken($token, $secret);
  $client = new UnivapayClient($storeAppToken);

  // トークンを使用して支払いを行う
  $chargeAmount = Money::JPY(1000);
  return $client->createCharge($tokenResource->id, $chargeAmount);
}

■質問②
Githubの/examples/create_charge_and_refund.phpに記載のある、22行目と23行目のnullはなにをいれる引数でしょうか？
ここに金額や商品IDを指定して課金などができるのでしょうか？

**Comment by upc-tanaka** [comment]
@kyohey-dan 
お世話になっております。

 ■質問①
ダミーのコード内には、作成したトランザクショントークンIDと金額を入力して決済を行ってください。
商品IDを指定する項目ではございませんのご了承ください。

■質問②
トランザクショントークンの種類がリカーリングの場合、決済などの処理が使用可能な間隔を設定することができます。
制限をかける必要がない場合は指定する必要はございません。
https://docs.univapay.com/References/transaction-tokens/#:~:text=subscription%2C%20recurring-,usage_limit,-string%0Atype%20%E3%81%8C

以上、引き続き宜しくお願い致します。

**Comment by kyohey-dan** [comment]
@upc-tanaka 
お世話になっております。
お返事ありがとうございます！

まだ解決できてないことがございますのでご質問させていただきます。
結論から申し上げますと、
現在私が作っているコードはone_timeの一回きりの1,000円を課金することしかできていないため、
以下のことを行いたいです。
①定期課金を行う方法を知りたいです。新管理画面のテスト課金にある決済詳細（課金間隔や初回課金金額や定期課金金額や開始日や回数など）にあるものをPHPで指定して課金させたいのです。

```
function executePayment($tokenResource)
{
  // テスト環境用のアプリトークン
  $token = '';
  $secret = '';

  $storeAppToken = AppJWT::createToken($token, $secret);
  $client = new UnivapayClient($storeAppToken);

  // トークンを使用して支払いを行う
  $chargeAmount = Money::JPY(1000);
  return $client->createCharge($tokenResource->id, $chargeAmount);
}

```

**Comment by upc-tanaka** [comment]
@kyohey-dan 
回答にお時間をいただき申し訳ございません。
SDK内に定期課金の追加の記述例がありませんでしたので準備いたしました。

$charge = $client->createToken($paymentMethod)->createSubscription(
    Money::JPY(20000),
    Period::QUARTERLY(),
    Money::JPY(15000),
    new ScheduleSettings(
        date_create('+1 month') // Date to start the subscription after initial charge
    ),
    new SubscriptionPlan(
        SubscriptionPlanType::FIXED_CYCLES(),
        21 // The number of cycles including the first cycle of initial amount
    )
)->awaitResult(5);

create_subscription.php
https://github.com/univapay/univapay-php-sdk/blob/7a2062b909c620ac6b5f7b153a79fc4b3ea59c17/examples/create_subscription.php#L39-L50

インラインフォームでトークンIDを取得し、
呼び出して場合は $client->createSubscription をご利用ください。

    public function createSubscription(
        $transactionTokenId,
        Money $money,
        Period $period,
        Money $initialAmount = null,
        ScheduleSettings $scheduleSettings = null,
        SubscriptionPlan $subscriptionPlan = null,
        InstallmentPlan $installmentPlan = null,
        array $metadata = null
    ) {

UnivapayClient.php
https://github.com/univapay/univapay-php-sdk/blob/7a2062b909c620ac6b5f7b153a79fc4b3ea59c17/src/Univapay/UnivapayClient.php#L186-L195

**Comment by kyohey-dan** [comment]
@upc-tanaka 
お世話になっております。
お返事ありがとうございます！

こちらで試してみます！
大変助かりました！
