### ISSUE TITLE
メタデータを使ってChargesを取得できない

### ISSUE THREAD

**Issue by noadant** [univapay/univapay-php-sdk#51]
listChargesやlistChargesByOptionsではmetadataを指定して取得する際に配列を指定する必要があるが、
URLがmetadata[test]=testといった形になって弾かれます
SDKを使わずにmetadata=testとしたら問題なく取得ができました
これはバグでしょうか？

**Comment by kgston** [comment]
ご連絡ありがとうございます。
確かに言う通りarrayで送るのが微妙です。
含めてtransactionsのフィルターにもmetadata項目を追加します。

修正のPRをリリースまで少々お待ちください。
