### ISSUE TITLE
univapay-php-sdkのメタデータについて

### ISSUE THREAD

**Issue by Asura-Works** [univapay/univapay-php-sdk#55]
現在、PHP8系でunivapay-php-sdkを使い決済プログラムを開発しています。
単体課金とサブスク課金ともに決済は成功しているのですが、メタデータが送信できずに悩んでいます。

具体的にはメタデータを指定しても管理画面に反映されません。

```
$H_meta = [
    'key1' => 'value1',
    'key2' => 'value2',
];
```

のようなメタデータを作り以下のようにサブスクオブジェクトを生成します。

```
$paymentMethod = new CardPayment(
        $mail ,
        $card_holder ,
        $card_number ,
        $month ,
        $year ,
        $sec_code ,
        TokenType::SUBSCRIPTION(),
        null,
        $O_add,
        $O_tel,
        $H_meta ,
);
```

返却された「$paymentMethod」には「metadata」があります。
しかし、管理画面の定期課金の詳細ページのメタデータの項目には反映されません。

また、サブスク登録後に返却される結果には「metadata」が空っぽになってしまっています(決済は成功しています)。

PHPのメタデータについてのサンプルや資料がなく困っております。
メタデータが反映されないのはどのような原因が考えられるでしょうか？

**Comment by kgston** [comment]
ご連絡ありがとうございます。

例に見るとメタデータオブジェクトはトランザクショントークンを作成時に送っていますのでメタデータはトークンに紐づけています。サブスクに紐づけたいなら、別当でサブスクの作成時にメタデータオブジェクトを入れなければといけません。以下の169行目にご参考ください。
https://github.com/univapay/univapay-php-sdk/blob/05ce743209a6641c52952d1acc780e10e02b08c7/src/Univapay/Resources/TransactionToken.php#L162-L173

**Comment by Asura-Works** [comment]
ありがとうございます。

`$client->createToken`

の引数7番目にメタデータを指定しましたら成功しました！

**Comment by Asura-Works** [comment]
解決しましたのでクローズさせて頂きますm(_ _)m
